### ISSUE TITLE
WinSur dark/light

### ISSUE THREAD

**Issue by hexive** [yeyushengfan258/WinSur-dark-kde#3]
Are you the original author of the WinSur dark/light wallpapers? 

They are really beautiful and I think they'd be perfect to adapt into a full theme for Dynamic Desktop Wallpapers ([https://github.com/hexive/sunpaper](https://github.com/hexive/sunpaper)). Would you be interested in a commission to develop several sunrise sunset transitions? Or, alternatively, would you be open to sharing the original illustrator files for the images?

**Comment by yeyushengfan258** [comment]
Yes, I can share it with you and I will upload the source file later.

**Comment by hexive** [comment]
got the svg. thank you!
