### ISSUE TITLE
Plasma 5.25

### ISSUE THREAD

**Issue by Earthquake125** [yeyushengfan258/WinSur-dark-kde#9]
Hello,

Can you please update this theme for plasma 5.25? 

+ More info can be found here:
https://psifidotos.blogspot.com/2022/03/kornersfix.html?m=1

+ Maybe this commit can be used as reference
https://github.com/paulmcauley/classik/commit/fe48c052f529e889706214c9af3db200fbfdb2a8

![image](https://user-images.githubusercontent.com/59297679/174452969-0d930bc0-c697-419a-a213-b3ec0af59968.png)

**Comment by yeyushengfan258** [comment]
Has been updated, I just recently upgraded to this version.
